FROM gcr.io/deeplearning-platform-release/tf-cpu.2-13

# Install Python packages
RUN pip install -U google-cloud-aiplatform shapely==1.8.5 protobuf kfp==1.8.22 google-cloud-bigquery
ENTRYPOINT ["/bin/bash"]
